import { test } from "node:test";
import assert from "node:assert/strict";
import {
  AtomicCommandGate,
  CommandConflictError,
  StaleVersionError,
  fingerprintCommand,
  type CanonicalCommandInput,
} from "../src/storage/atomic-command-gate.js";

function baseInput(overrides: Partial<CanonicalCommandInput> = {}): CanonicalCommandInput {
  return {
    aggregateKey: "aggregate-1",
    operation: "CREATE",
    actorId: "actor-1",
    payloadHash: "hash-1",
    expectedVersion: 0,
    ...overrides,
  };
}

// Invariant 8: fingerprint is generated by Foundation.
test("invariant 8: fingerprint is deterministic over the canonical fields", () => {
  const a = fingerprintCommand(baseInput());
  const b = fingerprintCommand(baseInput());
  assert.equal(a, b);
  assert.equal(a.length, 64);
});

// Invariant 9: same canonical command replays.
test("invariant 9: same idempotency key + same canonical command replays prior result", async () => {
  const gate = new AtomicCommandGate();
  let calls = 0;
  const mutate = () => {
    calls += 1;
    return { value: calls };
  };
  const first = await gate.execute("key-1", baseInput(), mutate);
  const second = await gate.execute("key-1", baseInput(), mutate);
  assert.deepEqual(first, { value: 1 });
  assert.deepEqual(second, { value: 1 });
  assert.equal(calls, 1);
});

// Invariants 10-14: changed aggregate/operation/actor/payload/expectedVersion conflicts.
const conflictCases: Array<[string, Partial<CanonicalCommandInput>]> = [
  ["invariant 10: changed aggregate conflicts", { aggregateKey: "aggregate-2" }],
  ["invariant 11: changed operation conflicts", { operation: "UPDATE" }],
  ["invariant 12: changed actor conflicts", { actorId: "actor-2" }],
  ["invariant 13: changed payload conflicts", { payloadHash: "hash-2" }],
];

for (const [name, override] of conflictCases) {
  test(name, async () => {
    const gate = new AtomicCommandGate();
    await gate.execute("key-1", baseInput(), () => "first");
    await assert.rejects(() => gate.execute("key-1", baseInput(override), () => "second"), CommandConflictError);
  });
}

test("invariant 14: changed expected version conflicts", async () => {
  const gate = new AtomicCommandGate();
  await gate.execute("key-1", baseInput({ expectedVersion: 0 }), () => "first");
  await assert.rejects(
    () => gate.execute("key-1", baseInput({ expectedVersion: 1 }), () => "second"),
    CommandConflictError,
  );
});

// Invariant 15: stale version prevents mutation callback from executing.
test("invariant 15: stale version prevents the mutation callback from executing", async () => {
  const gate = new AtomicCommandGate();
  await gate.execute("key-1", baseInput({ expectedVersion: 0 }), () => "first");
  let called = false;
  await assert.rejects(
    () =>
      gate.execute("key-2", baseInput({ expectedVersion: 0 }), () => {
        called = true;
        return "second";
      }),
    StaleVersionError,
  );
  assert.equal(called, false);
});

// Invariant 16: concurrent duplicate executes the mutation once in the reference adapter.
test("invariant 16: concurrent duplicate calls execute the mutation exactly once", async () => {
  const gate = new AtomicCommandGate();
  let calls = 0;
  const mutate = async () => {
    calls += 1;
    await new Promise((resolve) => setTimeout(resolve, 10));
    return { value: calls };
  };
  const [a, b] = await Promise.all([
    gate.execute("key-1", baseInput(), mutate),
    gate.execute("key-1", baseInput(), mutate),
  ]);
  assert.equal(calls, 1);
  assert.deepEqual(a, b);
});

// PR-A review finding 4: unambiguous fingerprint serialization. A naive delimiter-joined
// concatenation lets distinct canonical tuples collide on serialized bytes (e.g. a value that
// contains the delimiter shifts a field boundary). A length-prefixed/unambiguous encoding must
// keep these distinct.
test("finding 4: fingerprint does not collide across a field-boundary-shifting delimiter", () => {
  const a = fingerprintCommand(
    baseInput({ aggregateKey: "a b", operation: "c", actorId: "x", payloadHash: "y", expectedVersion: 0 }),
  );
  const b = fingerprintCommand(
    baseInput({ aggregateKey: "a", operation: "b c", actorId: "x", payloadHash: "y", expectedVersion: 0 }),
  );
  assert.notEqual(a, b);
});

test("finding 4: reusing an idempotency key across a boundary-shifting collision conflicts, not replays", async () => {
  const gate = new AtomicCommandGate();
  await gate.execute(
    "key-1",
    baseInput({ aggregateKey: "a b", operation: "c", actorId: "x", payloadHash: "y", expectedVersion: 0 }),
    () => "first",
  );
  await assert.rejects(
    () =>
      gate.execute(
        "key-1",
        baseInput({ aggregateKey: "a", operation: "b c", actorId: "x", payloadHash: "y", expectedVersion: 0 }),
        () => "second",
      ),
    CommandConflictError,
  );
});

// PR-A review finding 6: same-aggregate race across DIFFERENT idempotency keys. Two distinct
// commands targeting the same aggregate at the same expectedVersion must not both commit —
// exactly one may execute its mutation callback; the loser must see a stale-version rejection
// and must not have executed its mutation callback.
test("finding 6: same-aggregate concurrent commands under different idempotency keys — exactly one commits", async () => {
  const gate = new AtomicCommandGate();
  let mutationCalls = 0;
  const makeMutate = (label: string) => async () => {
    mutationCalls += 1;
    await new Promise((resolve) => setTimeout(resolve, 10));
    return label;
  };

  const results = await Promise.allSettled([
    gate.execute("key-a", baseInput({ expectedVersion: 0 }), makeMutate("a")),
    gate.execute("key-b", baseInput({ expectedVersion: 0 }), makeMutate("b")),
  ]);

  const fulfilled = results.filter((r) => r.status === "fulfilled");
  const rejected = results.filter((r) => r.status === "rejected");
  assert.equal(fulfilled.length, 1, "exactly one of the two racing commands must commit");
  assert.equal(rejected.length, 1, "the losing command must be rejected");
  assert.equal(mutationCalls, 1, "only the winning command's mutation callback may execute");
  assert.ok((rejected[0] as PromiseRejectedResult).reason instanceof StaleVersionError);
  assert.equal(gate.getAggregateVersion("aggregate-1"), 1);
});

// Round-2 review finding A: same idempotency key, DIFFERENT aggregateKey, concurrent execution.
// Round-1's fix only serialized per aggregateKey, so two different aggregates could each
// independently see "no receipt yet" and both execute their mutation callback. The locked
// contract requires: same key + changed aggregate -> conflict, and the idempotency mutation
// must not execute twice.
test("finding A: same idempotency key across different aggregates — exactly one commits, the other conflicts", async () => {
  const gate = new AtomicCommandGate();
  let mutationCalls = 0;
  const makeMutate = (label: string) => () => {
    mutationCalls += 1;
    return label;
  };

  const results = await Promise.allSettled([
    gate.execute("shared-key", baseInput({ aggregateKey: "aggregate-1", expectedVersion: 0 }), makeMutate("agg1")),
    gate.execute("shared-key", baseInput({ aggregateKey: "aggregate-2", expectedVersion: 0 }), makeMutate("agg2")),
  ]);

  const fulfilled = results.filter((r) => r.status === "fulfilled");
  const rejected = results.filter((r) => r.status === "rejected");
  assert.equal(fulfilled.length, 1, "exactly one of the two racing commands must commit");
  assert.equal(rejected.length, 1, "the competing changed-aggregate command must be rejected");
  assert.equal(mutationCalls, 1, "only the winning command's mutation callback may execute");
  assert.ok((rejected[0] as PromiseRejectedResult).reason instanceof CommandConflictError);
  // Exactly one of the two aggregates was actually mutated/version-incremented; the other
  // (whichever lost) must remain untouched.
  const versions = [gate.getAggregateVersion("aggregate-1"), gate.getAggregateVersion("aggregate-2")];
  assert.deepEqual(versions.sort(), [0, 1]);
});

// Preserve: same key + same canonical command concurrently still replays via one mutation call
// (re-asserted here alongside the new different-aggregate race coverage for regression safety).
test("finding A regression guard: same key + same aggregate + same command concurrently still executes once", async () => {
  const gate = new AtomicCommandGate();
  let mutationCalls = 0;
  const mutate = () => {
    mutationCalls += 1;
    return "result";
  };
  const [a, b] = await Promise.all([
    gate.execute("dup-key", baseInput({ aggregateKey: "aggregate-3", expectedVersion: 0 }), mutate),
    gate.execute("dup-key", baseInput({ aggregateKey: "aggregate-3", expectedVersion: 0 }), mutate),
  ]);
  assert.equal(mutationCalls, 1);
  assert.equal(a, "result");
  assert.equal(b, "result");
  assert.equal(gate.getAggregateVersion("aggregate-3"), 1);
});

// Round-3 review finding 1: byte-unambiguous canonical encoding. A length-prefix computed from
// JavaScript string .length (UTF-16 code units) but hashed via Node's default UTF-8 string
// encoding lets distinct lone surrogates collapse to the same UTF-8 replacement bytes (U+FFFD),
// producing identical hashed bytes for genuinely different runtime strings.
test("finding round3-1: fingerprint distinguishes canonical commands differing only by lone surrogate", () => {
  const a = fingerprintCommand(baseInput({ aggregateKey: "\uD800", operation: "op" }));
  const b = fingerprintCommand(baseInput({ aggregateKey: "\uD801", operation: "op" }));
  assert.notEqual(a, b);
});

test("finding round3-1: reusing an idempotency key across a lone-surrogate collision conflicts, mutation runs once", async () => {
  const gate = new AtomicCommandGate();
  let calls = 0;
  await gate.execute("key-1", baseInput({ aggregateKey: "\uD800", operation: "op" }), () => {
    calls += 1;
    return "first";
  });
  await assert.rejects(
    () =>
      gate.execute("key-1", baseInput({ aggregateKey: "\uD801", operation: "op" }), () => {
        calls += 1;
        return "second";
      }),
    CommandConflictError,
  );
  assert.equal(calls, 1, "the second (conflicting) command's mutation callback must not execute");
});
